export const IS_RESET_TOKEN_VALID = 'IS_RESET_TOKEN_VALID';
export const SET_POSTED_JOBS = 'SET_POSTED_JOBS';
export const SET_CANDIDATE_LIST = 'SET_CANDIDATE_LIST';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';